// Y8 Spring Student Data
const students = [
  { name: 'dina', grade: 'C3', class: '8s2', festival: 'Eid', photo: 'yes' },
  { name: 'emmanuel', grade: 'D1', class: '8s2', festival: 'Chinese New Year', photo: 'yes' },
  { name: 'summer', grade: 'D1', class: '8s2', festival: 'Halloween', photo: 'yes' },
  { name: 'saba', grade: 'D1', class: '8s2', festival: 'Sanrio Anniversary', photo: 'yes' },
  { name: 'aid', grade: 'D1', class: '8s2', festival: 'Ramadan', photo: 'yes' },
  { name: 'soufiana', grade: 'E1', class: '8s2', festival: '', photo: 'no' },
  { name: 'lorena', grade: 'B2', class: '8s2', festival: 'Halloween', photo: 'yes' },
  { name: 'victoria', grade: 'B2', class: '8s2', festival: 'Easter', photo: 'yes' },
  { name: 'eva', grade: 'B2', class: '8s2', festival: 'Chinese New Year', photo: 'yes' },
  { name: 'alea', grade: 'B3', class: '8s2', festival: 'Ramadan', photo: 'yes' },
  { name: 'nareece', grade: 'c1', class: '8s2', festival: 'Halloween', photo: 'yes' },
  { name: 'jannat', grade: 'C2', class: '8s2', festival: 'Eid', photo: 'yes' },
  { name: 'sajid', grade: 'C2', class: '8s2', festival: 'Chinese New Year', photo: 'yes' },
  { name: 'pogba', grade: 'D1', class: '8s2', festival: 'African Party Festival', photo: 'no' },
  { name: 'jazmin', grade: 'C3', class: '8s2', festival: 'Chinese New Year', photo: 'yes' },
  { name: 'artemis', grade: 'B3', class: '8s2', festival: 'Sanrio Anniversary', photo: 'yes' },
  { name: 'mubasher', grade: 'B3', class: '8s5', festival: 'Fortnite Festival', photo: 'yes' },
  { name: 'ghena', grade: 'd1', class: '8s5', festival: 'Ramadan', photo: 'no' },
  { name: 'avy', grade: 'B3', class: '8s5', festival: 'Christmas', photo: 'yes' },
  { name: 'alyha', grade: 'C3', class: '8s5', festival: 'Sakura Festival', photo: 'yes' },
  { name: 'amirali', grade: 'D1', class: '8s5', festival: 'Ramadan', photo: 'no' },
  { name: 'arianna', grade: 'D1', class: '8s5', festival: 'International Cat Day', photo: 'yes' },
  { name: 'jacek', grade: 'D1', class: '8s5', festival: 'Christmas', photo: 'yes' },
  { name: 'matthew', grade: 'D1', class: '8s5', festival: 'Christmas', photo: 'no' },
  { name: 'rayan', grade: 'D1', class: '8s5', festival: 'International Cat Day', photo: 'yes' },
  { name: 'nethumi', grade: 'B2', class: '8s5', festival: 'Easter', photo: 'yes' },
  { name: 'richard', grade: 'C1', class: '8s5', festival: 'Christmas', photo: 'yes' },
  { name: 'oltiana', grade: 'C3', class: '8s5', festival: 'Sakura Festival', photo: 'yes' },
  { name: 'shauna', grade: 'D3', class: '8s5', festival: 'Christmas', photo: 'yes' },
  { name: 'mohaisany', grade: 'D1', class: '8s5', festival: 'Ramadan', photo: 'yes' },
  { name: 'hydeia', grade: 'B2', class: '8s5', festival: 'Philippine Independence Day', photo: 'yes' },
  { name: 'hannah', grade: 'C1', class: '8h5', festival: 'Christmas', photo: 'yes' },
  { name: 'shivan', grade: 'D1', class: '8h5', festival: 'Halloween', photo: 'yes' },
  { name: 'hamza', grade: 'C2', class: '8h5', festival: 'London Clown Festival', photo: 'yes' },
  { name: 'esha', grade: 'B3', class: '8h5', festival: 'Diwali', photo: 'yes' },
  { name: 'adam', grade: 'C2', class: '8h5', festival: 'Eid', photo: 'yes' },
  { name: 'arushi', grade: 'C1', class: '8h5', festival: 'Easter', photo: 'yes' },
  { name: 'renushian', grade: 'C2', class: '8h5', festival: '', photo: 'yes' },
  { name: 'fatma', grade: 'D2', class: '8h5', festival: 'Christmas', photo: 'yes' },
  { name: 'barbod', grade: 'D1', class: '8h5', festival: 'Nowruz', photo: 'yes' },
  { name: 'lulian', grade: 'C2', class: '8h5', festival: 'Halloween', photo: 'yes' },
  { name: 'sudais', grade: 'C3', class: '8h5', festival: 'Eid', photo: 'yes' },
  { name: 'wojtek', grade: 'D3', class: '8h5', festival: '', photo: 'yes' },
  { name: 'aaliyah', grade: 'D1', class: '8h5', festival: 'Ramadan', photo: 'yes' },
  { name: 'mawa', grade: 'D2', class: '8h2', festival: 'Ramadan', photo: 'yes' },
  { name: 'zubaidah', grade: 'D3', class: '8h2', festival: '', photo: 'no' },
  { name: 'danah', grade: 'D3', class: '8h2', festival: 'Ramadan', photo: 'no' },
  { name: 'haider', grade: 'D1', class: '8h2', festival: 'Christmas', photo: 'yes' },
  { name: 'sayed', grade: 'C2', class: '8h2', festival: 'Eid', photo: 'yes' },
  { name: 'amelie', grade: 'D2', class: '8h2', festival: 'Christmas', photo: 'yes' },
  { name: 'nathan', grade: 'D2', class: '8h2', festival: 'Chinese New Year', photo: 'yes' },
  { name: 'armand', grade: 'C2', class: '8h2', festival: 'Chinese New Year', photo: 'no' },
  { name: 'layla', grade: 'C3', class: '8h2', festival: 'Halloween', photo: 'yes' },
  { name: 'emil', grade: 'C2', class: '8h2', festival: 'Christmas', photo: 'yes' },
  { name: 'ari', grade: 'D2', class: '8h2', festival: 'Eid', photo: 'yes' },
  { name: 'rahman', grade: 'D1', class: '8h2', festival: 'Ramadan', photo: 'yes' },
  { name: 'mahdi', grade: 'D1', class: '8h2', festival: 'Eid', photo: 'yes' },
  { name: 'alma', grade: 'B3', class: '8h2', festival: 'Nowruz', photo: 'yes' },
  { name: 'hussain', grade: 'D2', class: '8h2', festival: 'Ramadan', photo: 'yes' },
  { name: 'diya', grade: 'D2', class: '8h2', festival: 'Halloween', photo: 'yes' },
  { name: 'Kelvin', grade: 'C3', class: '8h2', festival: 'Chinese New Year', photo: 'no' },
  { name: 'kamsi', grade: 'D2', class: '8h2', festival: 'Christmas', photo: 'yes' }
]; 